# Site
name: '清风明月'
description: '清风明月博客是基于Mundana模板创建的个人博客，目的在于记录生活点滴，鼓励自己不断前进！'
logo: '/assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: ''
disqus: 'songzhijie-cn'
email: 'song_zhi_jie@163.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    seven:
      name:           seven
      site:           https://www.songzhijie.cn
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, 我是Seven, 是“清风明月”博客的创办人。希望通过该博客能记录我们生活中的点滴的同时，也能为正在阅读的你带来帮助!"
      email:          song_zhi_jie@163.com
      github:         https://github.com/ZhijieSong
      # twitter:        https://twitter.com/wowthemesnet

    lauro:
      name:           lauro
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar2.jpg
      bio:            "ly是我的爱人，在生活、工作和学习方面都给予了我极大的鼓励与支持!"
      # email:          fakemail@gmail.com
      # twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: seven
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: GFM
highlighter: rouge
# kramdown:
#   auto_ids:         true
#   footnote_nr:      1
#   entity_output:    as_char
#   toc_levels:       1..6
#   enable_coderay:   false
# mathjax:            true
# sass:
#   sass_dir:         _sass
#   style:            compressed

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
theme: jekyll-theme-cayman
